# in openapi.yaml, we don't have definitions section and instead it's components
class ReferenceFixer
  def walk(root)
    visit(root)
  end

  private

  def visit(data)
    case data
    when Array
      data.each { visit(_1) }
    when Hash
      if data.keys == ['$ref']
        data['$ref'].sub!('#/definitions/', '#/components/schemas/')
      else
        data.each_value { visit(_1) }
      end
    else
      data
    end
  end
end

class InvalidKeysRemover
  def walk(root)
    visit(root)
  end

  private

  def visit(data)
    case data
    when Array
      data.each { visit(_1) }
    when Hash
      # AllowScFileUploads is an exception that doesn't need to have `type` but the source data has it...
      # https://github.com/slackapi/java-slack-sdk/blob/6f67d62486cd4b7a4d17e9a7de54db462a263e7a/slack-api-client/src/main/java/com/slack/api/methods/response/team/external_teams/TeamExternalTeamsListResponse.java#L84-L89
      data['AllowScFileUploads']['properties'].delete('type') if data.key?('AllowScFileUploads')

      data.each_value { visit(_1) }
    else
      data
    end
  end
end

# In common Slack response, `ok` always exists
class OptionalityFixer
  def walk(root)
    visit(root)
  end

  private

  def visit(data)
    case data
    when Array
      data.each { visit(_1) }
    when Hash
      if data.keys.include?('properties') && data.keys.include?('required')
        if data['properties'].keys.include?('ok')
          data['required'].append('ok')
          data['required'].uniq!
        end

        if data['properties']['type'] && data['properties']['type']['type'] == 'string'
          data['required'].append('type')
          data['required'].uniq!
        end
      end

      # Additional properties should be allowed but don't need to be decoded
      data.delete('additionalProperties') if data.key?('additionalProperties')

      data.each_value { visit(_1) }
    else
      data
    end
  end
end

# Quicktype doesn't convert key's case
class SnakeCaseToCamelCaseConverter
  def walk(root)
    visit(root['definitions'])
  end

  private

  def visit(data)
    case data
    when Array
      data.each { visit(_1) }
    when Hash
      data.keys.each do |key|
        value = data[key]
        visit(value)
        next unless key.match?(/_/)

        camel_case_key = key.camelize
        data[camel_case_key] = value
        data.delete(key)
      end
    else
      data
    end
  end
end

# Force UpperCamelCase for acronyms; ie DND -> Dnd
# quicktype unintentionally choose capital case for acronyms
class AcronymsFixer
  def initialize(dictionary)
    @dictionary = dictionary
  end

  def walk(root)
    visit(root)
  end

  private

  def visit(data)
    case data
    when Array
      data.each { visit(_1) }
    when Hash
      data.keys.each do |key|
        value = data[key]
        visit(value)
        acronyms = @dictionary.keys.find { key =~ /#{_1}/ }
        next unless acronyms

        correct_case = @dictionary[acronyms]
        camel_case_key = key.gsub(acronyms) { correct_case }
        data[camel_case_key] = value
        data.delete(key)
      end
    else
      if data.is_a?(String) && acronyms = @dictionary.keys.find { data =~ /#{_1}/ }
        correct_case = @dictionary[acronyms]
        data.gsub!(acronyms) { correct_case }
      else
        data
      end
    end
  end
end

# Fix type generated by quicktype
class TypeFixer
  def walk(root)
    visit(root)
  end

  private

  def visit(data)
    case data
    when Array
      data.each { visit(_1) }
    when Hash
      data.keys.each do |key|
        case key
        when 'View', 'Block'
          # View and Block should be implemented by SlackBlockKit.
          # To remove relevant schemas used within View and Block but proceed with swift-openapi-generator,
          # empty View and Block and eventually remove generated code in different script.
          data[key] = {
            type: 'object',
            properties: {},
            additionalProperties: true
          }
        when 'Subteam'
          # Subteam is Usergroup
          data['Usergroup'] = data['Subteam']
        when 'Root'
          # Root should be called MessageRoot (for threads)
          data['MessageRoot'] = data['Root']
        when 'properties'
          data[key]&.each_key do |prop_name|
            # Match property name and corresponding type.
            # quicktype produces wrong types due to inconsistency in sample json in java-slack-sdk.
            case prop_name
            when /.*block$/i
              data[key][prop_name]['$ref'] = '#/components/schemas/Block'
            when /.*blocks$/i
              data[key][prop_name]['items']['$ref'] = '#/components/schemas/Block'
            when /.*message$/i
              data[key][prop_name]['$ref'] = '#/components/schemas/Message'
            when /^messages$/
              # when messages array's element is object and not string type
              if data[key][prop_name].dig('items', '$ref')
                data[key][prop_name]['items']['$ref'] = '#/components/schemas/Message'
              end
            when /^subteam$/
              # Subteam is actually Usergroup
              # https://docs.slack.dev/reference/events/subteam_updated
              if data[key][prop_name].key?('$ref')
                data[key][prop_name]['$ref'] = '#/components/schemas/Usergroup'
              end
            when /^root$/
              # Subteam is actually Usergroup
              # https://docs.slack.dev/reference/events/subteam_updated
              if data[key][prop_name]['$ref'] == '#/components/schemas/Root'
                data[key][prop_name]['$ref'] = '#/components/schemas/MessageRoot'
              end
            when /^workflow_draft_configuration$/, /^workflow_published_configuration$/
              # Workflow(Publish)Configuration and WorkflowDraftConfiguration is same
              if data[key][prop_name].key?('$ref')
                data[key][prop_name]['$ref'] = '#/components/schemas/WorkflowConfiguration'
              end
            when /^priority$/
              # Channel's priority is a float (eg. 0.123456789), but sample data in
              # java-slack-sdk always shows it as 0, so quicktype infers integer.
              if data[key][prop_name]['type'] == 'integer'
                data[key][prop_name]['type'] = 'number'
              end
            end
          end
        end
      end
      data.each_value { visit(_1) }
    else
      data
    end
  end
end

class UserProfileRefFixer
  TARGET_SCHEMAS = %w[User Member InvitingUser TingUser].freeze

  def walk(root)
    definitions = root['definitions']
    return unless definitions.is_a?(Hash)

    ensure_user_profile_schema(definitions)

    TARGET_SCHEMAS.each do |schema_name|
      profile_ref = definitions.dig(schema_name, 'properties', 'profile', '$ref')
      next unless profile_ref == '#/components/schemas/Profile'

      definitions[schema_name]['properties']['profile']['$ref'] = '#/components/schemas/UserProfile'
    end
  end

  private

  def ensure_user_profile_schema(definitions)
    return if definitions.key?('UserProfile')

    definitions['UserProfile'] = if definitions.key?('Profile')
                                   Marshal.load(Marshal.dump(definitions['Profile']))
                                 else
                                   {
                                     'type' => 'object',
                                     'properties' => {},
                                     'additionalProperties' => true
                                   }
                                 end
  end
end

class TeamProfileRefFixer
  TARGET_SCHEMA = 'TeamProfileGetResponse'.freeze

  def walk(root)
    definitions = root['definitions']
    return unless definitions.is_a?(Hash)

    ensure_team_profile_schema(definitions)

    profile_ref = definitions.dig(TARGET_SCHEMA, 'properties', 'profile', '$ref')
    return unless profile_ref == '#/components/schemas/Profile'

    definitions[TARGET_SCHEMA]['properties']['profile']['$ref'] = '#/components/schemas/TeamProfile'
  end

  private

  def ensure_team_profile_schema(definitions)
    return if definitions.key?('TeamProfile')

    definitions['TeamProfile'] = if definitions.key?('Profile')
                                   Marshal.load(Marshal.dump(definitions['Profile']))
                                 else
                                   {
                                     'type' => 'object',
                                     'properties' => {},
                                     'additionalProperties' => true
                                   }
                                 end
  end
end

# Hand-written models live in Sources/SlackModels; ref fixers point inferred
# references at them and leave this placeholder so the OpenAPI document stays
# valid. The generated Swift type is dropped by SlackModelsExtractor.
module HandwrittenModel
  def self.placeholder_schema
    {
      'type' => 'object',
      'properties' => {},
      'additionalProperties' => true
    }
  end
end

# calls.* responses use the Calls API call object, which is the hand-written
# SlackModels.Call (com.slack.api.model.Call in java-slack-sdk). Message call
# blocks also define a `Call` with an unrelated shape, so every inferred `Call`
# is emptied, like View and Block in TypeFixer, and its nested schemas are
# removed as orphans.
class CallRefFixer
  def walk(root)
    definitions = root['definitions']
    return unless definitions.is_a?(Hash) && definitions.key?('Call')

    definitions['Call'] = HandwrittenModel.placeholder_schema
  end
end

# api.test echoes its arguments in `args`, which quicktype names `Args`. Use the
# hand-written SlackModels.APITestArgs (ApiTestResponse.Args in java-slack-sdk).
class APITestArgsRefFixer
  TARGET_SCHEMA = 'APITestResponse'.freeze

  def walk(root)
    definitions = root['definitions']
    return unless definitions.is_a?(Hash)

    args_ref = definitions.dig(TARGET_SCHEMA, 'properties', 'args', '$ref')
    return unless args_ref == '#/components/schemas/Args'

    definitions[TARGET_SCHEMA]['properties']['args']['$ref'] = '#/components/schemas/APITestArgs'
    definitions.delete('Args')
    definitions['APITestArgs'] = HandwrittenModel.placeholder_schema
  end
end

# admin.workflows.search returns app workflows, which quicktype names `Workflow`
# like several unrelated shapes in other responses. Use the hand-written
# SlackModels.AppWorkflow (com.slack.api.model.admin.AppWorkflow in
# java-slack-sdk) and keep this response's `Workflow` out of the shared schemas.
class AppWorkflowRefFixer
  TARGET_SCHEMA = 'AdminWorkflowsSearchResponse'.freeze

  def walk(root)
    definitions = root['definitions']
    return unless definitions.is_a?(Hash)

    items = definitions.dig(TARGET_SCHEMA, 'properties', 'workflows', 'items')
    return unless items.is_a?(Hash) && items['$ref'] == '#/components/schemas/Workflow'

    items['$ref'] = '#/components/schemas/AppWorkflow'
    remove_unreferenced(definitions, from: 'Workflow')
    definitions['AppWorkflow'] = HandwrittenModel.placeholder_schema
  end

  private

  # Removes the replaced definition and the nested definitions only it used
  # (Icons, Step, ...), so they cannot win shared name collisions.
  def remove_unreferenced(definitions, from:)
    candidates = [from] + referenced_names(definitions, from)
    definitions.delete(from)
    candidates.each do |name|
      still_used = definitions.any? { |other, _| other != name && referenced_names(definitions, other, [other]).include?(name) }
      definitions.delete(name) unless still_used
    end
  end

  def referenced_names(definitions, name, seen = [name])
    definitions.fetch(name, {}).to_json.scan(%r{"#/components/schemas/([^"]+)"}).flatten.uniq.flat_map do |child|
      next [] if seen.include?(child)

      [child] + referenced_names(definitions, child, seen + [child])
    end.uniq
  end
end

# Usergroup responses each contain a different subset of fields, so the merged
# `Usergroup` kept only the fields of the last fixture. Use the hand-written
# SlackModels.Usergroup (com.slack.api.model.Usergroup in java-slack-sdk).
class UsergroupRefFixer
  def walk(root)
    definitions = root['definitions']
    return unless definitions.is_a?(Hash) && definitions.key?('Usergroup')

    definitions['Usergroup'] = HandwrittenModel.placeholder_schema
  end
end

# admin.workflows.collaborators.* report per-user failures in `errors`, whose
# items quicktype names `Error` like unrelated error shapes in other responses.
# Use the hand-written SlackModels.WorkflowCollaboratorError.
class WorkflowCollaboratorErrorRefFixer
  TARGET_SCHEMAS = %w[
    AdminWorkflowsCollaboratorsAddResponse
    AdminWorkflowsCollaboratorsRemoveResponse
  ].freeze

  def walk(root)
    definitions = root['definitions']
    return unless definitions.is_a?(Hash)

    TARGET_SCHEMAS.each do |schema_name|
      items = definitions.dig(schema_name, 'properties', 'errors', 'items')
      next unless items.is_a?(Hash) && items['$ref'] == '#/components/schemas/Error'

      items['$ref'] = '#/components/schemas/WorkflowCollaboratorError'
      definitions.delete('Error')
      definitions['WorkflowCollaboratorError'] = HandwrittenModel.placeholder_schema
    end
  end
end

# Add optional ts property to Item schema for reaction events compatibility
class ItemTsOptionalAdder
  def walk(root)
    visit(root)
  end

  private

  def visit(data)
    case data
    when Array
      data.each { visit(_1) }
    when Hash
      # Target the Item schema specifically
      if data.key?("Item") && data["Item"].is_a?(Hash)
        item_schema = data["Item"]
        if item_schema.key?("properties")
          # Add ts property as optional if it does not exist
          unless item_schema["properties"].key?("ts")
            item_schema["properties"]["ts"] = { "type" => "string" }
          end
          # Ensure ts is NOT in required fields (keep it optional)
          if item_schema["required"]&.include?("ts")
            item_schema["required"].delete("ts")
          end
        end
      end

      data.each_value { visit(_1) }
    else
      data
    end
  end
end
