#!/usr/bin/env ruby
# frozen_string_literal: true

# Splits the Swift code that Apple's swift-openapi-generator emits for .tmp/WebAPI/openapi.json into the
# downstream swift-slack source tree:
#
#   Sources/SlackClient/WebAPI/Generated/
#     APIProtocol.swift, Servers.swift
#     Client/Client+Base.swift, Client/Client+<Group>.swift          (one trait per API group)
#     Operations/Operations+Base.swift, Operations/Operations+<Group>.swift
#     Components/Components+Base.swift, Components/Components+<Group>.swift  (<Method>Response types)
#     Models/<Name>.swift, Models/Typealiases.swift                   (shared models, also used by events)
#   Sources/SlackApp/Events/Generated/
#     <Name>Event.swift, Event.swift                                  (events, behind the Events trait)
#   Tests/SlackClientTests/Generated/ResponseFixtureDecoders.swift   (for scripts/check_fixtures.rb)
#
# It also updates the list of Web API traits in Package.swift.
#
# Usage: process_webapi.rb <generator output dir> <openapi.json>

require 'fileutils'
require 'json'
require 'set'
require_relative 'lib/swift_declarations'

# Repository sources are UTF-8; do not depend on the caller's locale.
Encoding.default_external = Encoding::UTF_8

ROOT_DIR = File.expand_path('..', __dir__)

class UnknownAPIGroupError < StandardError; end

# The top-level Web API groups advertised by upstream slack-api-ref. Keeping this data in the vendor
# instead of a hand-maintained list lets a newly added Slack group participate in generation automatically.
module APIGroups
  VENDOR_GROUPS_DIRECTORY = File.join(ROOT_DIR, 'vendor/slack-api-ref/groups')
  # Generated names whose prefix is not the group name.
  PREFIX_ALIASES = { 'slacklists' => 'lists' }.freeze
  # Trait and file names spell some groups differently from `capitalize`.
  DISPLAY_NAMES = { 'dnd' => 'DND', 'oauth' => 'OAuth', 'openid' => 'OpenID', 'rtm' => 'RTM' }.freeze

  module_function

  def all(directory = VENDOR_GROUPS_DIRECTORY)
    @all ||= {}
    @all[directory] ||= begin
      groups = Dir.glob(File.join(directory, '**', '*.json')).filter_map do |path|
        JSON.parse(File.read(path))['name']&.split('.')&.first
      end
      raise "No API groups found in #{directory}" if groups.empty?

      groups.uniq
    end
  end

  # The group of a generated name such as `chatPostMessage`, `ChatPostMessage` or `ChatPostMessageResponse`.
  def group_for(name, groups: all)
    normalized = name.downcase
    PREFIX_ALIASES.each { |prefix, group| return group if normalized.start_with?(prefix) }
    groups.find { |group| normalized.start_with?(group.downcase) } or
      raise UnknownAPIGroupError, "Unable to determine Slack API group for #{name}"
  end

  def display_name(group)
    DISPLAY_NAMES.fetch(group) { group.capitalize }
  end

  def trait(group)
    "WebAPI_#{display_name(group)}"
  end
end

# Updates the generated list of Web API traits in Package.swift.
module PackageTraits
  module_function

  def update(package_file, groups)
    content = File.read(package_file)
    traits = groups.sort.map { |group| "    \"#{APIGroups.trait(group)}\"," }.join("\n")
    section = <<~SWIFT.strip
      // BEGIN: Generated WebAPI traits - Do not edit manually
      let webAPITraits: [String] = [
      #{traits}
      ]

      var traits: [Trait] = webAPITraits.map { .trait(name: $0) }
      // END: Generated WebAPI traits
    SWIFT
    pattern = %r{// BEGIN: Generated WebAPI traits.*?// END: Generated WebAPI traits}m
    raise "#{package_file} has no generated WebAPI traits section" unless content.match?(pattern)

    File.write(package_file, content.sub(pattern) { section })
    puts "Updated Package.swift with #{groups.size} WebAPI traits"
  end
end

# Writes files and removes the ones a previous run left behind.
class OutputDirectory
  def initialize(path)
    @path = path
    @written = Set.new
  end

  def write(relative, content)
    path = File.join(@path, relative)
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, content)
    @written << File.expand_path(path)
  end

  # Deletes .swift files under the directory that this run did not write.
  def remove_stale_files
    Dir.glob(File.join(@path, '**', '*.swift')).each do |path|
      File.delete(path) unless @written.include?(File.expand_path(path))
    end
  end
end

class WebAPIProcessor
  GENERATED_HEADER = "// Generated by swift-openapi-generator, do not modify.\n"
  # Names a top-level typealias must not take: common Swift standard library and Foundation types.
  RESERVED_NAMES = %w[
    Any Array Bool Character Codable Data Date Decoder Dictionary Double Encoder Error Float Int Never Optional
    Range Result Set String Task Type URL UUID
  ].to_set.freeze

  def initialize(input_directory, openapi_path, client_directory:, events_directory:, tests_directory:, package_file:)
    @input_directory = input_directory
    @openapi = JSON.parse(File.read(openapi_path))
    @client = OutputDirectory.new(client_directory)
    @events = OutputDirectory.new(events_directory)
    @tests = OutputDirectory.new(tests_directory)
    @package_file = package_file
  end

  def run
    header, declarations = SwiftDeclarations.split(read_lines('Types.swift'), indent: 0)
    @header = header.join
    protocol, protocol_extension = declarations.select { |declaration| declaration.name == 'APIProtocol' }

    write_api_protocol(protocol, protocol_extension)
    write_declaration_file('Servers.swift', declarations.find { |declaration| declaration.name == 'Servers' })
    write_components(declarations.find { |declaration| declaration.name == 'Components' })
    write_operations(declarations.find { |declaration| declaration.name == 'Operations' })
    groups = write_client
    PackageTraits.update(@package_file, groups)
    write_response_decoders

    @client.remove_stale_files
    @events.remove_stale_files
    @tests.remove_stale_files
  end

  private

  def read_lines(name)
    File.readlines(File.join(@input_directory, name))
  end

  def write_declaration_file(name, declaration)
    @client.write(name, @header + declaration.text)
  end

  def response_type(path_item)
    path_item.dig('post', 'responses', '200', 'content', 'application/json', 'schema', '$ref').split('/').last
  end

  # ---------------------------------------------------------------- APIProtocol

  # APIProtocol with every requirement and convenience overload behind its group's trait.
  def write_api_protocol(protocol, protocol_extension)
    content = [protocol, protocol_extension].map { |declaration| with_member_traits(declaration) }.join("\n")
    @client.write('APIProtocol.swift', @header.sub(GENERATED_HEADER, "#{GENERATED_HEADER}// swiftformat:disable all\n") + content)
  end

  # The declaration with consecutive members of one API group wrapped in `#if <trait>`.
  def with_member_traits(declaration)
    _, members = SwiftDeclarations.split(SwiftDeclarations.body(declaration), indent: 4)
    opening = declaration.lines.take_while { |line| SwiftDeclarations.comment?(line) }
    opening << declaration.lines[opening.size]
    body = members.chunk_while { |a, b| APIGroups.group_for(a.name) == APIGroups.group_for(b.name) }.map do |chunk|
      trait = APIGroups.trait(APIGroups.group_for(chunk.first.name))
      "    #if #{trait}\n#{chunk.map(&:text).join}    #endif\n"
    end
    opening.join + body.join + "}\n"
  end

  # ---------------------------------------------------------------- Components

  def write_components(components)
    _, sections = SwiftDeclarations.split(SwiftDeclarations.body(components), indent: 4)
    schemas_section = sections.find { |section| section.name == 'Schemas' }
    _, schemas = SwiftDeclarations.split(SwiftDeclarations.body(schemas_section), indent: 8)

    responses, events, models, aliases = classify(schemas)
    @client.write('Components/Components+Base.swift', components_base(aliases))
    write_responses(responses)
    write_models(models)
    write_events(events)
  end

  # Splits the schema declarations into responses, events, shared models and the typealiases that
  # typeOverrides emits for SlackBlockKit types.
  def classify(schemas)
    response_names = @openapi['paths'].values.map { |path_item| response_type(path_item) }.to_set
    event_names = @openapi.fetch('x-slack-events').keys.to_set
    aliases, types = schemas.partition { |schema| schema.text.match?(/^ {8}public typealias /) }
    responses = types.select { |schema| response_names.include?(schema.name) }
    events = types.select { |schema| event_names.include?(schema.name) }
    [responses, events, types - responses - events, aliases]
  end

  def components_base(aliases)
    <<~SWIFT
      #{@header}/// Types generated from the components section of the OpenAPI document.
      public enum Components {
          /// Types generated from the `#/components/schemas` section of the OpenAPI document.
          public enum Schemas {
      #{aliases.map(&:text).join}    }
      }
    SWIFT
  end

  # `<Method>Response` types, one file per API group behind its trait.
  def write_responses(responses)
    responses.group_by { |schema| APIGroups.group_for(schema.name) }.sort.each do |group, schemas|
      @client.write("Components/Components+#{APIGroups.display_name(group)}.swift",
                    "#{@header}\n#if #{APIGroups.trait(group)}\nextension Components.Schemas {\n" \
                    "#{schemas.map(&:text).join}}\n#{schemas.map { |schema| dictionary_subscripts(schema) }.join}" \
                    "#endif\n")
    end
  end

  # Shared models, one file each, and a top-level typealias for each so apps can write `User`.
  def write_models(models)
    models.each do |schema|
      @client.write("Models/#{schema.name}.swift",
                    "#{@header}\nextension Components.Schemas {\n#{schema.text}}\n#{accessors(schema)}#{dictionary_subscripts(schema)}")
    end
    names = models.map(&:name).sort
    check_typealias_names(names)
    aliases = names.map { |name| "public typealias #{name} = Components.Schemas.#{name}\n" }
    @client.write('Models/Typealiases.swift', "#{GENERATED_HEADER}\n#{aliases.join}")
  end

  # Read-only properties for the alternatives of a `oneOf` schema, named by its `x-swift-accessors`
  # (scripts/handwritten_schemas.yml): `value.html` instead of `if case let .case1(html) = value`.
  def accessors(schema)
    names = @openapi.dig('components', 'schemas', schema.name, 'x-swift-accessors') or return ''
    cases = schema.text.scan(/^ {12}case (case\d+)\((.+)\)$/)
    raise "#{schema.name}: #{names.size} accessors for #{cases.size} cases" unless names.size == cases.size

    properties = names.zip(cases).filter_map do |name, (case_name, type)|
      next unless name

      "    public var #{name}: #{type}? {\n        if case let .#{case_name}(value) = self { value } else { nil }\n    }\n"
    end
    "\nextension Components.Schemas.#{schema.name} {\n#{properties.join("\n")}}\n"
  end

  # `subscript(key:)` for every generated struct that only wraps a typed `additionalProperties` dictionary (a
  # Java `Map<String, T>`), so `profile.fields?["Xf1"]` reads like a dictionary lookup. Returns Swift source.
  def dictionary_subscripts(schema)
    dictionary_wrappers(schema, "Components.Schemas.#{schema.name}", 8).map do |type_name, value_type|
      "\nextension #{type_name} {\n" \
        "    public subscript(key: Swift.String) -> #{value_type}? {\n" \
        "        additionalProperties[key]\n" \
        "    }\n}\n"
    end.join
  end

  # [[qualified type name, value type]] of the dictionary wrappers among `declaration` (declared at `indent`)
  # and the types nested in it.
  def dictionary_wrappers(declaration, type_name, indent)
    _, members = SwiftDeclarations.split(SwiftDeclarations.body(declaration), indent: indent + 4)
    properties = members.select { |member| member.text.match?(/^ {#{indent + 4}}public var /) }
    wrappers = []
    if properties.map(&:name) == ['additionalProperties'] &&
       (value_type = properties.first.text[/public var additionalProperties: \[(?:Swift\.)?String: (.+)\]$/, 1])
      wrappers << [type_name, value_type]
    end
    members.each do |member|
      next unless member.text.match?(/^ {#{indent + 4}}(?:@frozen )?public (?:struct|enum) /)

      wrappers.concat(dictionary_wrappers(member, "#{type_name}.#{member.name}", indent + 4))
    end
    wrappers
  end

  # Fails when a top-level typealias would clash with a standard type or another module's public type.
  def check_typealias_names(names)
    taken = RESERVED_NAMES | handwritten_public_types
    clashes = names.select { |name| taken.include?(name) }
    raise "Shared model names clash with existing top-level types: #{clashes.join(', ')}" unless clashes.empty?
  end

  # Public top-level type names declared in hand-written sources of every module.
  def handwritten_public_types
    Dir.glob(File.join(ROOT_DIR, 'Sources', '**', '*.swift')).reject { |path| path.include?('/Generated/') }
       .each_with_object(Set.new) do |path, names|
      File.read(path).scan(/^public (?:struct|enum|class|actor|protocol|typealias) (\w+)/) { |(name)| names << name }
    end
  end

  # ---------------------------------------------------------------- Events

  # One file per event in SlackApp, behind the Events trait, conforming to SlackEvent.
  def write_events(events)
    events.each do |schema|
      @events.write("#{schema.name}.swift", <<~SWIFT)
        #if Events
        #{@header}import SlackClient

        extension Components.Schemas {
        #{schema.text}}

        public typealias #{schema.name} = Components.Schemas.#{schema.name}

        extension Components.Schemas.#{schema.name}: SlackEvent {}
        #{dictionary_subscripts(schema)}#endif
      SWIFT
    end
    @events.write('Event.swift', EventEnum.new(@openapi.fetch('x-slack-events')).source)
  end

  # ---------------------------------------------------------------- Fixture decoders

  # Method name => decoder of its response type, for FixtureDecodingTests.
  def write_response_decoders
    by_trait = @openapi['paths'].sort.group_by do |_, item|
      APIGroups.trait(APIGroups.group_for(response_type(item)))
    end
    sections = by_trait.map do |trait, paths|
      assignments = paths.map do |path, item|
        "    decoders[\"#{path.delete_prefix('/')}\"] = { try JSONDecoder().decode(Components.Schemas.#{response_type(item)}.self, from: $0) }\n"
      end
      "    #if #{trait}\n#{assignments.join}    #endif\n"
    end
    @tests.write('ResponseFixtureDecoders.swift', <<~SWIFT)
      // Generated by scripts/process_webapi.rb, do not modify.
      import Foundation
      import SlackClient

      /// Decodes the response of each generated Web API method, by method name.
      let responseFixtureDecoders: [String: @Sendable (Data) throws -> Any] = {
          var decoders: [String: @Sendable (Data) throws -> Any] = [:]
      #{sections.join}    return decoders
      }()
    SWIFT
  end

  # ---------------------------------------------------------------- Operations

  def write_operations(operations)
    opening = operations.lines.take_while { |line| SwiftDeclarations.comment?(line) }
    @client.write('Operations/Operations+Base.swift', "#{@header}#{opening.join}public enum Operations {}\n")
    _, members = SwiftDeclarations.split(SwiftDeclarations.body(operations), indent: 4)
    members.group_by { |member| APIGroups.group_for(member.name) }.sort.each do |group, group_members|
      @client.write("Operations/Operations+#{APIGroups.display_name(group)}.swift",
                    "#{@header}\n#if #{APIGroups.trait(group)}\nextension Operations {\n" \
                    "#{group_members.map(&:text).join}}\n#endif\n")
    end
  end

  # ---------------------------------------------------------------- Client

  # Client+Base.swift keeps the stored properties and initializer; each group's methods go to an extension
  # behind its trait. Returns the API groups.
  def write_client
    header, declarations = SwiftDeclarations.split(read_lines('Client.swift'), indent: 0)
    client = declarations.find { |declaration| declaration.name == 'Client' } or raise 'Client.swift has no Client'
    opening = client.lines.take_while { |line| SwiftDeclarations.comment?(line) }
    opening << client.lines[opening.size]
    _, members = SwiftDeclarations.split(SwiftDeclarations.body(client), indent: 4)
    methods, base = members.partition { |member| member.text.match?(/^ {4}internal func /) }

    # Extensions in other files use these, so they cannot stay private.
    base_text = base.map { |member| member.text.gsub(/^    private (let|var) /, '    internal \1 ') }.join
    @client.write('Client/Client+Base.swift', header.join + opening.join + base_text + "}\n")

    methods.group_by { |method| APIGroups.group_for(method.name) }.sort.map do |group, group_methods|
      @client.write("Client/Client+#{APIGroups.display_name(group)}.swift",
                    "#if #{APIGroups.trait(group)}\n#{header.join}\nextension Client {\n" \
                    "#{group_methods.map(&:text).join}}\n#endif\n")
      group
    end
  end
end

# The `Event` enum that decodes any generated event by its `type` (and, for messages, `subtype`).
class EventEnum
  # `events`: schema name => { "type" => ..., "subtype" => ... } (openapi.json `x-slack-events`).
  def initialize(events)
    @events = events.sort.to_h
  end

  def source
    <<~SWIFT
      #if Events
      import Foundation

      /// Polymorphic event type that can decode any Slack event based on the type field
      public enum Event: Decodable, Hashable, Sendable {
      #{@events.keys.map { |name| "    case #{case_name(name)}(#{name})" }.join("\n")}
          case unsupported(String)

          public init(from decoder: Decoder) throws {
              let container = try decoder.container(keyedBy: CodingKeys.self)
              let type = try container.decode(String.self, forKey: .type)

              switch type {
      #{type_cases.join("\n")}
              default:
                  self = .unsupported(type)
              }
          }

          /// Returns the contained event as a SlackEvent
          public var payload: (any SlackEvent)? {
              switch self {
      #{@events.keys.map { |name| "        case .#{case_name(name)}(let event):\n            return event" }.join("\n")}
              case .unsupported:
                  return nil
              }
          }

          private enum CodingKeys: String, CodingKey {
              case type
          }

          private enum SubtypeCodingKeys: String, CodingKey {
              case subtype
          }
      }
      #endif
    SWIFT
  end

  private

  # `IMCloseEvent` => "imClose", `ChannelIDChangedEvent` => "channelIdChanged"
  def case_name(schema_name)
    words = schema_name.delete_suffix('Event').gsub('ID', 'Id').gsub('IM', 'Im').scan(/[A-Z][a-z0-9]*/)
    words.first.downcase + words.drop(1).join
  end

  # One `case "<type>":` per event type; a type with subtypes switches on `subtype` as well.
  def type_cases
    @events.group_by { |_, event| event['type'] }.sort.map do |type, events|
      plain = events.reject { |_, event| event['subtype'] }
      with_subtype = events.select { |_, event| event['subtype'] }
      raise "several events have type #{type} and no subtype" if plain.size > 1

      if with_subtype.empty?
        "        case \"#{type}\":\n            self = try .#{case_name(plain[0][0])}(#{plain[0][0]}(from: decoder))"
      else
        subtype_switch(type, plain.first&.first, with_subtype)
      end
    end
  end

  # `case "message":` switching on `subtype`; an event without a subtype handles `subtype == nil`.
  def subtype_switch(type, plain_name, with_subtype)
    cases = with_subtype.sort_by { |_, event| event['subtype'] }.map do |name, event|
      "    case \"#{event['subtype']}\":\n        self = try .#{case_name(name)}(#{name}(from: decoder))"
    end
    nil_case = plain_name ? "self = try .#{case_name(plain_name)}(#{plain_name}(from: decoder))" : 'self = .unsupported(type)'
    lines = [
      "case \"#{type}\":",
      '    let subtype = try decoder.container(keyedBy: SubtypeCodingKeys.self)',
      '        .decodeIfPresent(String.self, forKey: .subtype)',
      '    switch subtype {',
      *cases,
      '    case nil:',
      "        #{nil_case}",
      '    case let .some(unknownSubtype):',
      "        self = .unsupported(\"#{type} - \\(unknownSubtype)\")",
      '    }',
    ]
    lines.map { |line| "        #{line}" }.join("\n")
  end
end

if $PROGRAM_NAME == __FILE__
  unless ARGV.size == 2
    warn 'Usage: process_webapi.rb <generator output dir> <openapi.json>'
    exit 1
  end

  WebAPIProcessor.new(
    ARGV[0], ARGV[1],
    client_directory: File.join(ROOT_DIR, 'Sources/SlackClient/WebAPI/Generated'),
    events_directory: File.join(ROOT_DIR, 'Sources/SlackApp/Events/Generated'),
    tests_directory: File.join(ROOT_DIR, 'Tests/SlackClientTests/Generated'),
    package_file: File.join(ROOT_DIR, 'Package.swift')
  ).run
end
